enabled: true
top_level_version: false
github:
  position: 'off'
  tree: 'https://github.com/getgrav/grav-skeleton-rtfm-site/blob/develop/'
  commits: 'https://github.com/getgrav/grav-skeleton-rtfm-site/commits/develop/'
streams:
  schemes:
    theme:
      type: ReadOnlyStream
      paths:
        - user/themes/learn2
